"""
Poolside gate bridge — runs on the club's on-site Windows PC.

Polls the Poolside cloud every POLL_SEC seconds for pending gate-unlock
commands and runs the proven 2-step HTTP recipe against the panel on the
club's LAN. Translated from the field-tested Bishop Estates v0.4 bridge,
re-pointed at Poolside's per-bridge auth model (X-Bridge-Id +
X-Bridge-Secret) instead of using the service-role key.

Auth posture:
  - The bridge knows ONLY its own bridge_id + bridge_secret.
  - If the Pi is stolen, the attacker can only fire unlock commands at this
    one tenant's panel. They can't read anyone's data.
  - The bridge_secret is generated by clicking "Rotate bridge secret" in
    the Poolside admin → Settings → 🔐 Remote keyfob access card. The
    plaintext is shown ONCE; if you lose it, rotate again.

Config: see .env.example. Run as a Windows service via nssm — see README.md.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from urllib.parse import urlencode

import requests
from dotenv import load_dotenv

# Load .env from the script's own directory (so the nssm service finds it
# regardless of where it was started from).
_HERE = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(_HERE, ".env"))

LOG = logging.getLogger("poolside_gate_bridge")
_log_path = os.path.join(_HERE, "bridge.log")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(_log_path, encoding="utf-8"),
    ],
)

# ── Required config ────────────────────────────────────────────────────
SUPABASE_URL  = os.environ["SUPABASE_URL"].rstrip("/")
BRIDGE_ID     = os.environ["BRIDGE_ID"]
BRIDGE_SECRET = os.environ["BRIDGE_SECRET"]

# ── Tunables (defaults work for typical small clubs) ───────────────────
POLL_SEC          = float(os.environ.get("POLL_SEC", "1.5"))
HEARTBEAT_SEC     = int(os.environ.get("HEARTBEAT_SEC", "30"))
STALE_COMMAND_SEC = int(os.environ.get("STALE_COMMAND_SEC", "60"))
BRIDGE_VERSION    = "1.0.0-poolside"

# ── Cloud endpoint ─────────────────────────────────────────────────────
CLOUD_URL = f"{SUPABASE_URL}/functions/v1/gate_bridge"
CLOUD_HEADERS = {
    "Content-Type": "application/json",
    "X-Bridge-Id": BRIDGE_ID,
    "X-Bridge-Secret": BRIDGE_SECRET,
}


# =============================================================================
# Panel adapter — the proven 2-step POST recipe.
# =============================================================================
# This block is copied verbatim from Bishop Estates' battle-tested code. Do
# not "improve" it — every quirk (the magic logId, the requests.Session for
# cookie persistence, the explicit form encoding) was earned through hours
# of troubleshooting against the real MENGQI-CONTROL HXC-7000 panel.
#
# Panel firmware tested: 2.4.7 (Bishop Estates).
# =============================================================================

PANEL_LOG_ID = "20101222"  # Panel-side magic constant — not a date, not random.

def unlock_panel(host: str, user: str, pwd: str, door: int = 1) -> tuple[bool, str]:
    """Open the gate. Returns (ok, detail). Never raises."""
    if not host:
        return False, "panel host not configured in Poolside admin"
    s = requests.Session()
    base = f"http://{host}"
    try:
        # Step 1 — login. Sets a session cookie on the requests.Session.
        # Panel rejects step 2 without this cookie.
        r1 = s.post(
            f"{base}/ACT_ID_1",
            data=urlencode({"username": user, "pwd": pwd, "logId": PANEL_LOG_ID}),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            timeout=5,
        )
        if r1.status_code != 200:
            return False, f"login HTTP {r1.status_code}"

        # Step 2 — actually open the gate. UNCLOSE1 = door 1; the value is
        # a label that shows up in the panel's local audit log.
        r2 = s.post(
            f"{base}/ACT_ID_701",
            data=urlencode({f"UNCLOSE{door}": f"Remote Open #{door} Door Main Gate"}),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            timeout=5,
        )
        if r2.status_code != 200:
            return False, f"unlock HTTP {r2.status_code}"
        return True, "panel returned 200"
    except requests.RequestException as e:
        return False, f"panel unreachable: {e}"


# =============================================================================
# Cloud client — talks to Poolside's gate_bridge edge function.
# =============================================================================

def cloud(action: str, **extra) -> tuple[int, dict]:
    """POST to the gate_bridge endpoint. Returns (status_code, body_dict).
    Never raises — returns (0, {error: ...}) on network failure."""
    body = {"action": action, **extra}
    if action == "heartbeat":
        body["version"] = BRIDGE_VERSION
    try:
        r = requests.post(CLOUD_URL, headers=CLOUD_HEADERS, data=json.dumps(body), timeout=10)
        try:
            return r.status_code, r.json()
        except ValueError:
            return r.status_code, {"raw": r.text[:200]}
    except requests.RequestException as e:
        return 0, {"error": str(e)}


# =============================================================================
# Main loop.
# =============================================================================

def is_stale(requested_at_iso: str | None) -> bool:
    """A command is stale if it was queued before the bridge was last alive.
    Without this guard, a bridge that was offline for an hour comes back
    and fires the panel 30 times in rapid succession when it picks up the
    backlog. Stolen from Bishop Estates' hard-won abort_stale_pending."""
    if not requested_at_iso:
        return False
    try:
        # Tolerate trailing 'Z' (Postgres) or +00:00 (newer Postgres versions)
        ts = requested_at_iso.replace("Z", "+00:00")
        when = datetime.fromisoformat(ts)
        age = (datetime.now(timezone.utc) - when).total_seconds()
        return age > STALE_COMMAND_SEC
    except ValueError:
        return False


def main() -> None:
    LOG.info(f"Poolside gate bridge {BRIDGE_VERSION} starting")
    LOG.info(f"  cloud:  {CLOUD_URL}")
    LOG.info(f"  bridge: {BRIDGE_ID}")
    LOG.info(f"  poll every {POLL_SEC}s, heartbeat every {HEARTBEAT_SEC}s")

    # First contact — also serves as a sanity check that creds are right.
    # 401 is fatal: bridge_id/secret are wrong, no point burning CPU on a
    # cred that will never start working. 403 is NON-fatal as of 2026-05-23:
    # it means the platform admin hasn't flipped this tenant to 'active'
    # yet, but they probably will soon — the bridge just sits there polling
    # and picks up the moment activation happens. Exiting on 403 used to
    # cause "service failed to start" right after install, because the
    # natural flow is install → start service → THEN activate.
    code, resp = cloud("heartbeat")
    if code == 401:
        LOG.error("Auth failed (401). Check BRIDGE_ID and BRIDGE_SECRET in .env.")
        LOG.error("If your secret was lost, rotate it in Poolside admin → Settings → 🔐 Remote keyfob access.")
        sys.exit(2)
    if code == 403:
        LOG.warning("Tenant gate add-on is not 'active' yet — staying alive and polling.")
        LOG.warning("Once the platform admin clicks '🟢 Activate gate' in /admin/gate-integrations.html,")
        LOG.warning("the next poll succeeds automatically. No restart needed.")
    elif code != 200:
        LOG.warning(f"First heartbeat returned {code}: {resp.get('error', resp)}. Will keep trying...")
    else:
        LOG.info("First heartbeat ok — credentials accepted.")

    last_hb = time.time()
    while True:
        try:
            now = time.time()

            # Heartbeat tick (poll itself updates last_seen, so this is mostly
            # for runs where there's no work for long stretches AND we want
            # the admin UI to keep showing 🟢 online). Cheap.
            if now - last_hb >= HEARTBEAT_SEC:
                cloud("heartbeat")
                last_hb = now

            # Poll for work. This call ALSO updates last_seen on the cloud
            # side, which is why most clubs won't ever hit the heartbeat path.
            code, resp = cloud("poll")
            if code != 200:
                LOG.warning(f"poll {code}: {resp.get('error', resp)}")
                time.sleep(POLL_SEC)
                continue

            command = resp.get("command")
            if not command:
                time.sleep(POLL_SEC)
                continue

            cmd_id = command.get("id")
            tenant = resp.get("tenant", {})

            # Stale guard — if we've been offline and the cloud handed us a
            # ten-minute-old request, don't fire it. Mark as 'stale' so the
            # admin sees it in the audit log but the gate stays closed.
            if is_stale(command.get("requested_at")):
                LOG.info(f"Skipping stale command {cmd_id[:8]}... (queued before bridge came online)")
                cloud("complete", unlock_id=cmd_id, result_code="stale",
                      result_detail=f"command older than {STALE_COMMAND_SEC}s when bridge polled")
                continue

            is_test = bool(command.get("is_test"))
            LOG.info(f"Picked up unlock {cmd_id[:8]}... {'(admin test)' if is_test else ''}")

            # Run the proven recipe.
            ok, detail = unlock_panel(
                host=tenant.get("panel_host") or "",
                user=tenant.get("panel_admin_user") or "admin",
                pwd=tenant.get("panel_admin_password") or "",
            )
            result_code = "ok" if ok else "panel_unreachable" if "unreachable" in detail else "panel_failed"
            cloud("complete", unlock_id=cmd_id, result_code=result_code, result_detail=detail)
            LOG.info(f"  → {result_code}: {detail}")

            time.sleep(POLL_SEC)

        except KeyboardInterrupt:
            LOG.info("Interrupted, exiting cleanly")
            return
        except Exception as e:
            LOG.exception(f"Loop error (continuing): {e}")
            time.sleep(POLL_SEC)


if __name__ == "__main__":
    main()
